import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ReactNode } from "react";
import { Poppins } from 'next/font/google';
import ThreeDCardScene from "@/components/ThreeDCard/index";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Teerachaya's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${poppins.className} scroll-smooth`}>
      <body className="bg-white text-gray-800">
        <Navbar />
        <ThreeDCardScene />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
